"""empty message

Revision ID: 2578ac540d1c
Revises: 15e58df04e43
Create Date: 2024-07-13 01:04:42.072792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2578ac540d1c'
down_revision = '15e58df04e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review', sa.String(length=500), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_games')
    # ### end Alembic commands ###
