"""empty message
Revision ID: 27ddbb153709
Revises: aa57928b7c81
Create Date: 2024-07-02 20:24:13.021659
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '27ddbb153709'
down_revision = 'aa57928b7c81'
branch_labels = None
depends_on = None

def upgrade():
    # Drop tables if they exist
    
    
    
    
    

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('genre', sa.String(), nullable=False),
        sa.Column('rating', sa.Float(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('popularity', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Mygames',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('favorite', sa.Boolean(), nullable=True),
        sa.Column('review', sa.String(), nullable=True),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
        sa.Column('follower_id', sa.Integer(), nullable=False),
        sa.Column('followed_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.alter_column('password',
            existing_type=sa.VARCHAR(length=80),
            type_=sa.String(length=256),
            existing_nullable=False)
        batch_op.create_unique_constraint('uq_user_username', ['username'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.alter_column('password',
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=80),
            existing_nullable=False)
        batch_op.drop_column('username')
    op.create_table('users',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('email', sa.VARCHAR(length=120), nullable=False),
        sa.Column('username', sa.VARCHAR(length=120), nullable=False),
        sa.Column('password', sa.VARCHAR(length=256), nullable=False),
        sa.Column('is_active', sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    op.drop_table('followers')
    op.drop_table('favorites')
    op.drop_table('Mygames')
    op.drop_table('game')
    # ### end Alembic commands ###